# Generated by Django 5.2.15 on 2026-06-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(default=14)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_calories', models.IntegerField()),
                ('daily_protein_g', models.IntegerField()),
                ('daily_carbs_g', models.IntegerField()),
                ('daily_fat_g', models.IntegerField()),
                ('daily_water_liters', models.FloatField()),
                ('meal_plan', models.JSONField(default=list)),
                ('sport_recommendation', models.TextField(blank=True, default='')),
                ('general_advice', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diet Plan',
                'verbose_name_plural': 'Diet Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='', max_length=1)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='', max_length=20)),
                ('goal', models.CharField(blank=True, choices=[('lose_weight', 'Lose Weight'), ('maintain', 'Maintain'), ('gain_weight', 'Gain Weight'), ('build_muscle', 'Build Muscle')], default='', max_length=20)),
                ('work_type', models.CharField(blank=True, choices=[('sedentary', 'Sedentary'), ('standing', 'Standing'), ('physical', 'Physical'), ('mixed', 'Mixed')], default='', max_length=20)),
                ('work_hours_per_day', models.FloatField(blank=True, null=True)),
                ('sleep_hours_per_day', models.FloatField(blank=True, null=True)),
                ('water_liters_per_day', models.FloatField(blank=True, null=True)),
                ('does_sport', models.BooleanField(default=False)),
                ('sport_type', models.CharField(blank=True, max_length=255, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('food_allergies', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('water_liters', models.FloatField(default=0.0)),
                ('meals_followed', models.BooleanField(default=False)),
                ('workout_done', models.BooleanField(default=False)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, choices=[('good', 'Good'), ('normal', 'Normal'), ('bad', 'Bad')], max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Log',
                'verbose_name_plural': 'Daily Logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
